openapi: 3.0.0
info:
  title: My API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /hello:
    get:
      operationId: sayHello
      summary: Send Hello Message
      security: []
      parameters:
        - name: nickname
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad Request
        500:
          description: Internel Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internel Server Error
